--- #YAML:1.0
name:               POE-Filter-JSON-Incr
version:            0.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:        0
    JSON:              2.12
    namespace::clean:  0.08
    POE::Filter:       0
    Test::use::ok:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
