--- #YAML:1.0
name:                POE-Filter-JSON-Incr
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    JSON:                          2.09
    Mouse:                         0.04
    namespace::clean:              0.08
    POE::Filter:                   0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
